name: 코드 검증을 시작합니다.

on:
  # PR 이벤트가 발생할 때 액션 시작
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-xcproject:
    name: 앱프로젝트를 빌드합니다
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Xcode 15.0 선택
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: 빌드
        run: |
          xcodebuild build -project SwiftCinema.xcodeproj -scheme SwiftCinema -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest'
          cd ~/Library/Developer/Xcode/DerivedData/SwiftCinema-*/Build/Products/Debug-iphonesimulator/SwiftCinema.app
          if test -d /Frameworks; then
            echo "There's the framework here"
          else
            echo "There's no the framework here"
            exit 1
          fi

  
  build-package:
    name: 스위프트 패키지를 빌드 합니다
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Xcode 15.0 선택
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: 빌드
        run: |
          cd swift-cinema
          xcodebuild build -scheme swift-cinema -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest'
          
  
  test-package:
    name: 스위프트 패키지를 테스트 합니다
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Xcode 15.0 선택
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: 빌드
        run: |
          cd swift-cinema
          xcodebuild test -scheme FetcherTests -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest'
    
